/************************************************************************

   AvalonDock

   Copyright (C) 2007-2013 Xceed Software Inc.

   This program is provided to you under the terms of the New BSD
   License (BSD) as published at http://avalondock.codeplex.com/license 

   For more features, controls, and fast professional support,
   pick up AvalonDock in Extended WPF Toolkit Plus at http://xceed.com/wpf_toolkit

   Stay informed: follow @datagrid on Twitter or Like facebook.com/datagrids

  **********************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonDock.WinFormsTestApp.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<LayoutRoot xmlns:xsi=\"http://www.w3.org/" +
            "2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <RootP" +
            "anel Orientation=\"Horizontal\">\r\n    <LayoutDocumentPaneGroup Orientation=\"Horizo" +
            "ntal\">\r\n      <LayoutDocumentPane>\r\n        <LayoutDocument Title=\"Document 1\" I" +
            "sSelected=\"True\" ContentId=\"document1\" FloatingLeft=\"167\" FloatingTop=\"237\" Floa" +
            "tingWidth=\"327\" FloatingHeight=\"291\" LastActivationTimeStamp=\"09/03/2012 15:42:1" +
            "6\" />\r\n      </LayoutDocumentPane>\r\n      <LayoutDocumentPane>\r\n        <LayoutD" +
            "ocument Title=\"Document 2\" IsSelected=\"True\" IsLastFocusedDocument=\"True\" Conten" +
            "tId=\"document2\" FloatingLeft=\"265\" FloatingTop=\"250\" FloatingWidth=\"161\" Floatin" +
            "gHeight=\"291\" LastActivationTimeStamp=\"09/03/2012 15:42:16\" />\r\n      </LayoutDo" +
            "cumentPane>\r\n    </LayoutDocumentPaneGroup>\r\n    <LayoutAnchorablePaneGroup Orie" +
            "ntation=\"Vertical\" DockWidth=\"120\">\r\n      <LayoutAnchorablePane DockWidth=\"120\"" +
            " FloatingWidth=\"132\" FloatingHeight=\"291\" FloatingLeft=\"455\" FloatingTop=\"248\">\r" +
            "\n        <LayoutAnchorable CanHide=\"False\" AutoHideMinWidth=\"100\" AutoHideMinHei" +
            "ght=\"100\" Title=\"WinForms Window\" IsSelected=\"True\" ContentId=\"toolWindow3\" Floa" +
            "tingLeft=\"455\" FloatingTop=\"248\" FloatingWidth=\"132\" FloatingHeight=\"291\" CanClo" +
            "se=\"False\" LastActivationTimeStamp=\"09/03/2012 15:41:54\" />\r\n      </LayoutAncho" +
            "rablePane>\r\n      <LayoutAnchorablePaneGroup Orientation=\"Horizontal\" FloatingWi" +
            "dth=\"150\" FloatingHeight=\"143\" FloatingLeft=\"433\" FloatingTop=\"280\">\r\n        <L" +
            "ayoutAnchorablePane FloatingWidth=\"150\" FloatingHeight=\"143\" FloatingLeft=\"433\" " +
            "FloatingTop=\"280\">\r\n          <LayoutAnchorable AutoHideMinWidth=\"100\" AutoHideM" +
            "inHeight=\"100\" Title=\"Tool Window 2\" IsSelected=\"True\" ContentId=\"toolWindow2\" F" +
            "loatingLeft=\"433\" FloatingTop=\"280\" FloatingWidth=\"150\" FloatingHeight=\"143\" Las" +
            "tActivationTimeStamp=\"09/03/2012 15:41:56\" />\r\n        </LayoutAnchorablePane>\r\n" +
            "      </LayoutAnchorablePaneGroup>\r\n    </LayoutAnchorablePaneGroup>\r\n    <Layou" +
            "tAnchorablePane Id=\"5684e345-b25d-434f-912d-2392e7762d97\" DockWidth=\"138\" Floati" +
            "ngWidth=\"150\" FloatingHeight=\"143\" FloatingLeft=\"472\" FloatingTop=\"243\">\r\n      " +
            "<LayoutAnchorable AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Tool Win" +
            "dow 1\" IsSelected=\"True\" ContentId=\"toolWindow1\" FloatingLeft=\"472\" FloatingTop=" +
            "\"243\" FloatingWidth=\"150\" FloatingHeight=\"143\" LastActivationTimeStamp=\"09/03/20" +
            "12 15:41:57\" />\r\n    </LayoutAnchorablePane>\r\n  </RootPanel>\r\n  <TopSide />\r\n  <" +
            "RightSide />\r\n  <LeftSide>\r\n    <LayoutAnchorGroup>\r\n      <LayoutAnchorable Aut" +
            "oHideMinWidth=\"300\" AutoHideMinHeight=\"100\" Title=\"AutoHide1 Content\" ContentId=" +
            "\"AutoHide1Content\" />\r\n      <LayoutAnchorable AutoHideMinWidth=\"100\" AutoHideMi" +
            "nHeight=\"100\" Title=\"AutoHide2 Content\" ContentId=\"AutoHide2Content\" />\r\n    </L" +
            "ayoutAnchorGroup>\r\n  </LeftSide>\r\n  <BottomSide />\r\n  <FloatingWindows />\r\n  <Hi" +
            "dden />\r\n</LayoutRoot>\r\n")]
        public string DefaultLayout {
            get {
                return ((string)(this["DefaultLayout"]));
            }
            set {
                this["DefaultLayout"] = value;
            }
        }
    }
}
